### ISSUE TITLE
If earlier non-cucumber tests task fails, then cucumber task won't run

### ISSUE THREAD

**Issue by dnwe** [samueltbrown/gradle-cucumber-plugin#51]
This may be a documentation-thing or something already built-in to gradle that I'm not aware of, but:

If you have a project with a mixture of junit unittests separate from the cucumber acceptance tests, and you invoke the build with (e.g.,) `gradle test cucumber check`, then the cucumber task won't actually run at all if any of the earlier tests fail.

Is it possible to always run the cucumber task even if earlier tests failed?

**Comment by marc0der** [comment]
I'd think that early failure is sensible, that's why Gradle has this behaviour. If you have failing (cheap) unit tests, you wouldn't want to advance to the expensive acceptance tests because you can't release the software anyway.

If however you _do_ want to run the cukes despite failing unit tests, you could just run `gradle cucumber`.

**Comment by dnwe** [comment]
`gradle --continue` sort of covers this use case anyway so closing off this old issue
